server:
  port: 8081
spring:
  # 数据源设置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # characterEncoding=utf-8 设置编码，serverTimezone=Asia/Shanghai 设置时区
    url: jdbc:mysql://localhost:3306/search?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 19491001
  jpa:
    database: mysql
    show-sql: true
